### ISSUE TITLE
Add TrimBlocks settings to the environment

### ISSUE THREAD

**Issue by kyleconroy** [NikolaLohinski/gonja#8]
Jinja2 environments support a [trim_blocks](https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment) setting.

```
trim_blocks:
  If this is set to True the first newline after a block is removed (block, not variable tag!). Defaults to False.
```

Could this option be added to the environment? I'm using this package to replicate a templating system that has this option on by default.

**Comment by NikolaLohinski** [comment]
Hey, sure. I removed all trimming capabilities when I took over the maintenance of the repo because they were poorly implemented. But we could bring them back.

If you feel like making a PR then I would happily help you get it merged. 

I am currently busy with cleaning the tests and fixing bugs while moving to the terraform plug-in framework. But after that I might have time to look into putting back trimming features.

**Comment by NikolaLohinski** [comment]
Hi @kyleconroy 

I've just pushed v2.0.0 which has the feature you requested.

This is major one, so the upgrade might not be trivial, but I've put [these small steps](https://github.com/NikolaLohinski/gonja?tab=readme-ov-file#migrating-from-v1-to-v2) together to help you out.

Let me know if you run into any issues and feel free to reopen the issue.

Cheers
